version: "3"
secrets:
  aws_priv_key: 
    file: ./.AWS_PRIV_KEY
  aws_access_id: 
    file: ./.AWS_ACCESS_ID
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 7CdNsT3pTbFd45r
      POSTGRES_USER: admin
      POSTGRES_DB: closed-flights
    ports:
      - 13001:5432
  app:
    image: node-app
    volumes:
      - .:/usr/src/app
    ports:
      - 13000:3000
    secrets:
      - aws_priv_key
      - aws_access_id
      
