version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 7CdNsT3pTbFd45r
      POSTGRES_USER: admin
      POSTGRES_DB: globetrotter
    ports:
      - 13001:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build:
      context: ./
    image: node-app
    volumes:
      - ./:/usr/src/app
    ports:
      - 13000:3000
    environment:
      - DATABASE_URL=postgres://admin:7CdNsT3pTbFd45r@db:5432/globetrotter
    depends_on:
      - db
    networks:
      - app-network
    
  # frontend:
  #   build:
  #     context: ./front
  #   ports:npm 
  #     - 3000:80
  #   networks:
  #     - app-network

networks:
  app-network:

volumes:
  postgres-data: